project_id = "yxjhungswhwahnbhahaq"

[functions.generate-ppt-from-template]
verify_jwt = false

[functions.generate-ppt-from-user-template]
verify_jwt = false

[functions.extract-template-styles]
verify_jwt = false

[functions.parse-ppt-template]
verify_jwt = false
